/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as TableRouteImport } from './routes/table'
import { Route as BuildStepIdRouteImport } from './routes/build.$stepId'
import { Route as NotesSectionIdRouteImport } from './routes/notes.$sectionId'
import { Route as WhyQuestionIdRouteImport } from './routes/why.$questionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildStepIdRoute = BuildStepIdRouteImport.update({
  id: '/build/$stepId',
  path: '/build/$stepId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesSectionIdRoute = NotesSectionIdRouteImport.update({
  id: '/notes/$sectionId',
  path: '/notes/$sectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyQuestionIdRoute = WhyQuestionIdRouteImport.update({
  id: '/why/$questionId',
  path: '/why/$questionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/table': typeof TableRoute
  '/build/$stepId': typeof BuildStepIdRoute
  '/notes/$sectionId': typeof NotesSectionIdRoute
  '/why/$questionId': typeof WhyQuestionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/table': typeof TableRoute
  '/build/$stepId': typeof BuildStepIdRoute
  '/notes/$sectionId': typeof NotesSectionIdRoute
  '/why/$questionId': typeof WhyQuestionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/table': typeof TableRoute
  '/build/$stepId': typeof BuildStepIdRoute
  '/notes/$sectionId': typeof NotesSectionIdRoute
  '/why/$questionId': typeof WhyQuestionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playground'
    | '/table'
    | '/build/$stepId'
    | '/notes/$sectionId'
    | '/why/$questionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/table'
    | '/build/$stepId'
    | '/notes/$sectionId'
    | '/why/$questionId'
  id:
    | '__root__'
    | '/'
    | '/playground'
    | '/table'
    | '/build/$stepId'
    | '/notes/$sectionId'
    | '/why/$questionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaygroundRoute: typeof PlaygroundRoute
  TableRoute: typeof TableRoute
  BuildStepIdRoute: typeof BuildStepIdRoute
  NotesSectionIdRoute: typeof NotesSectionIdRoute
  WhyQuestionIdRoute: typeof WhyQuestionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/$stepId': {
      id: '/build/$stepId'
      path: '/build/$stepId'
      fullPath: '/build/$stepId'
      preLoaderRoute: typeof BuildStepIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$sectionId': {
      id: '/notes/$sectionId'
      path: '/notes/$sectionId'
      fullPath: '/notes/$sectionId'
      preLoaderRoute: typeof NotesSectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why/$questionId': {
      id: '/why/$questionId'
      path: '/why/$questionId'
      fullPath: '/why/$questionId'
      preLoaderRoute: typeof WhyQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaygroundRoute: PlaygroundRoute,
  TableRoute: TableRoute,
  BuildStepIdRoute: BuildStepIdRoute,
  NotesSectionIdRoute: NotesSectionIdRoute,
  WhyQuestionIdRoute: WhyQuestionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
